use_frameworks!

target 'HGVideoPlayer_Example' do
  pod 'HGVideoPlayer', :path => '../'

#  target 'HGVideoPlayer_Tests' do
#    inherit! :search_paths
#
#    pod 'Specta'
#    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
#    pod 'Expecta+Snapshots'
#  end
end
